try {
  console.log(a);
} catch (error) {
  console.log(`something went wrong `);
}
//console.log(a);